service: bn-ddb-to-sqs

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  stage: prd
  environment:
    REGION: "us-east-1"
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
    - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
    - 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'

functions:

  # RSS Feeds
  getRSSFeedURLs:
    handler: ddbToSqs.handler
    events:
    - schedule:
        rate: rate(3 hours)
        enabled: true
    timeout: 25
    environment:
      TABLE_NAME: ${ssm:bnDDBPodcastTable}
      SQS_URL: ${ssm:bnSQSRSSQueueURL}
